apiVersion: batch/v1
kind: Job
metadata:
  name: {{ jobName }}
spec:
  #ttlSecondsAfterFinished: 100    
  template:
    spec:
      containers:
      - name: {{ jobName }}
        image: {{& imageSrc }}
        command: {{& command }}
        args: {{& args }}
        #resources:
          #limits:
            #nvidia.com/gpu: 1
      restartPolicy: Never
      #restartPolicy: OnFailure
  backoffLimit: 4